#!/bin/bash

# clone simengine repo from github,
# run the buildall script, and
# install the generated RPMs

REMOTE="git@github.com:Seneca-CDOT/simengine.git"
SE_DIR="${HOME}/simengine"
RPMS_DIR="${HOME}/rpmbuild/RPMS"

if [[ ! -d "${SE_DIR}" ]]; then
    git clone "${REMOTE}" "${SE_DIR}"
    echo "simengine repo cloned; please do not relocate the repo until the setup is over"
else
    echo "simengine repo appears to exist at ${SE_DIR}"
fi

cd "${SE_DIR}"

# ensure the simengine repo has the latest updates
# don't prune because we don't want to remove local copies of remote branches
# that may be used as backup
git fetch

simengine_latest_version=$(git \
    tag \
    --sort version:refname \
    | tail -1 \
)

echo "latest SimEngine version is [${simengine_latest_version}]"

git checkout "tags/${simengine_latest_version}"

if [[ ! -d "${RPMS_DIR}" ]]; then
    cd "${SE_DIR}/rpm/specfiles"
    ./buildall
else
    echo "rpms appears to exist at ${RPMS_DIR}"
fi

echo "sudo is required to install SimEngine RPMs"
sudo dnf install "${RPMS_DIR}"/**/simengine*-${simengine_latest_version}-*.rpm
